name: ecocaptura
description: "A field data capture app for Provita."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.0
  sensors_plus: ^7.0.0 
  flutter_compass: ^0.8.1
  camera: ^0.11.0+4
  json_annotation: ^4.9.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true